[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#5F9EA0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#50C878'

# Color used for almost all text
textColor = '#FFFFFF'
body {
    color = white
}

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
